/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.screen;

import br.certificate.CertificateDAO;
import br.document.Document;
import br.document.DocumentDAO;
import br.document.DocumentTableModel;
import br.location.Location;
import br.location.LocationDAO;
import br.location.LocationTableModel;
import br.person.Person;
import br.util.ConnectionFactory;
import br.util.EnviaEmails;
import br.util.FormataTamanhoColunasJTable;
import br.util.Util;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Pedro Saraiva
 */
public class FindDocumentFrm extends javax.swing.JDialog {

    public static void show(Person p) {
        person = p;
        new FindDocumentFrm().setVisible(true);

    }

    private static Person person;

    /**
     * Creates new form FindCertificatesFrm
     */
    public FindDocumentFrm() {
        initComponents();
        setTitle("Documentos");
        setModal(true);
        setLocationRelativeTo(null);
        lblPerson.setText(person.getNome().toString());

        insertTableDocuments();

        FormataTamanhoColunasJTable.packColumns(tbCertificates, 1);
        String texto = "";
        if (person.ispExterno()) {
            texto = "Público Externo";
        } else {
            texto = "Público Interno";
        }

        texto += "";

        lblInfo.setText(texto);
    }

    public void insertTableDocuments() {
        DocumentDAO lDAO = new DocumentDAO();

        List<Document> documents = lDAO.listPerPerson(person);

        DocumentTableModel ltm = new DocumentTableModel(documents);
        tbCertificates.setModel(ltm);
        FormataTamanhoColunasJTable.packColumns(tbCertificates, 1);
        tbCertificates.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCertificates = new javax.swing.JTable();
        lblInfo = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        lblPerson = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(59, 89, 152));
        jPanel3.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Consulta de Documentos");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(0, 0, 460, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(432, 177));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbCertificates.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCertificates.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCertificatesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbCertificatesMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tbCertificates);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 760, 230));

        lblInfo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblInfo.setText("lblInfo");
        jPanel1.add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 520, -1));

        jButton3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/SA.png"))); // NOI18N
        jButton3.setToolTipText("Sair");
        jButton3.setPreferredSize(new java.awt.Dimension(63, 39));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 57, 33));

        lblPerson.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblPerson.setText("Pessoa: ");
        jPanel1.add(lblPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 520, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbCertificatesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCertificatesMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {

            if (JOptionPane.showConfirmDialog(rootPane, "Deseja Enviar o Documento Novamente?", "Enviar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                int linha = tbCertificates.getSelectedRow();

                DocumentDAO ldao = new DocumentDAO();
                List<Document> documents = ldao.listPerPerson(person);
                DocumentTableModel ltm = new DocumentTableModel(documents);

                Document p = ltm.getDocumento(linha);
                String email = person.getEmail();
                if (email == null) {
                    email = "";
                }
                if (!email.isEmpty()) {
                    EnviaEmails.mandarEmail(person, p);
                    JOptionPane.showMessageDialog(rootPane, "Documento enviado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Atualize o E-mail da Pessoa!", "",
                            JOptionPane.ERROR_MESSAGE);
                }

            }
        }


    }//GEN-LAST:event_tbCertificatesMouseClicked

    private void tbCertificatesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCertificatesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tbCertificatesMouseEntered

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindDocumentFrm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindDocumentFrm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindDocumentFrm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindDocumentFrm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindDocumentFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblPerson;
    private javax.swing.JTable tbCertificates;
    // End of variables declaration//GEN-END:variables
}
