/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.screen;

import br.box.Box;
import br.box.BoxDAO;
import br.campus.Campus;
import br.campus.CampusDAO;
import br.certificate.Certificate;
import br.certificate.CertificateDAO;
import br.location.Location;
import br.location.LocationDAO;
import br.person.Person;
import br.person.PersonDAO;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro Saraiva
 */
public class RegisterLocationFrm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterCertificateFrm
     */
    public RegisterLocationFrm() {
        initComponents();
        setTitle("Localização de Certificados");
        setLocationRelativeTo(null);
        
        insertPersons();
        insertCertificates();
        insertBoxes();
        insertCampus();
    }
    
    private void insertCampus(){
        cbCampus.removeAllItems();
        cbCampus.addItem("-");
         
        CampusDAO pDAO = new CampusDAO();
        List<Campus> lista = pDAO.list("descricao");
        for (int i = 0; i < lista.size(); i++) {
            cbCampus.addItem(lista.get(i));
        }
    }
    
    private void insertPersons(){
        cbPerson.removeAllItems();
        cbPerson.addItem("-");
         
        PersonDAO pDAO = new PersonDAO();
        List<Person> lista = pDAO.list("nome");
        for (int i = 0; i < lista.size(); i++) {
            cbPerson.addItem(lista.get(i));
        }
    }
    
    private void insertCertificates(){
        cbCertificate.removeAllItems();
        cbCertificate.addItem("-");
         
        CertificateDAO cDAO = new CertificateDAO();
        List<Certificate> lista = cDAO.list("descricao");
        for (int i = 0; i < lista.size(); i++) {
            cbCertificate.addItem(lista.get(i));
        }
    }
    
    private void insertBoxes(){
        cbBox.removeAllItems();
        cbBox.addItem("-");
         
        BoxDAO bDAO = new BoxDAO();
        List<Box> lista = bDAO.list("descricao");
        for (int i = 0; i < lista.size(); i++) {
            cbBox.addItem(lista.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbPerson = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbCertificate = new javax.swing.JComboBox();
        cbBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbCampus = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Pessoa: *");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 41, -1, -1));

        cbPerson.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbPerson.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, 352, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Certificado: *");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, -1, -1));

        cbCertificate.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbCertificate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbCertificate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, 352, -1));

        cbBox.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 352, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Caixa: *");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 147, -1, -1));

        jPanel3.setBackground(new java.awt.Color(59, 89, 152));
        jPanel3.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Localização de Certificado");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(0, 0, 390, 30);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 35));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(432, 177));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/application-add-icon.png"))); // NOI18N
        jButton4.setToolTipText("Cadastrar Certificado");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 50, -1));

        jButton3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/application-add-icon.png"))); // NOI18N
        jButton3.setToolTipText("Cadastrar Pessoa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 50, 30));

        jButton5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/application-add-icon.png"))); // NOI18N
        jButton5.setToolTipText("Cadastrar Caixa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 50, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/confi.gif"))); // NOI18N
        jButton1.setToolTipText("Cadastrar Certificado");
        jButton1.setPreferredSize(new java.awt.Dimension(63, 39));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/SA.png"))); // NOI18N
        jButton2.setToolTipText("Sair");
        jButton2.setPreferredSize(new java.awt.Dimension(63, 39));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 130, 40));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/procurar_1.png"))); // NOI18N
        jButton6.setToolTipText("Pesquisar Certificado");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Campus: *");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        cbCampus.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbCampus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbCampus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 352, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 460, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        RegisterPersonFrm rpf = new RegisterPersonFrm();
        rpf.setVisible(true);
        
        insertPersons();
        insertBoxes();
        insertCertificates();
        insertCampus();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        RegisterCertificateFrm rcf = new RegisterCertificateFrm();
        rcf.setVisible(true);
        
        insertPersons();
        insertBoxes();
        insertCertificates();
        insertCampus();
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        RegisterBoxFrm rbf = new RegisterBoxFrm();
        rbf.setVisible(true);
        
        insertPersons();
        insertBoxes();
        insertCertificates();
        insertCampus();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(cbPerson.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "Informe a Pessoa!");
            cbPerson.requestFocus();
            return ;
        }
        FindCertificatesFrm.show((Person) cbPerson.getSelectedItem());
                
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(cbBox.getSelectedIndex()==0 || cbCertificate.getSelectedIndex()==0 
                || cbPerson.getSelectedIndex()==0 || cbCampus.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "Informe os Campos Obrigatórios (*)!");
            return ;
        }
        Location l = new Location();
        l.setBox((Box) cbBox.getSelectedItem());
        l.setCertificate((Certificate) cbCertificate.getSelectedItem());
        l.setPerson((Person) cbPerson.getSelectedItem());
        l.setEntregue(false);
        l.setCampus((Campus) cbCampus.getSelectedItem());
        
        LocationDAO lDAO = new LocationDAO();
        lDAO.add(l);
        
        cbBox.setSelectedIndex(0);
        cbPerson.setSelectedIndex(0);
        cbCertificate.setSelectedIndex(0);
        
        JOptionPane.showMessageDialog(rootPane, "Localização Cadastrada com Sucesso!");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterLocationFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterLocationFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterLocationFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterLocationFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterLocationFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbBox;
    private javax.swing.JComboBox cbCampus;
    private javax.swing.JComboBox cbCertificate;
    private javax.swing.JComboBox cbPerson;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
